
export const MONTHLY_HOUSEHOLD_FEE = 100;
export const MONTHLY_COMMERCIAL_INCOME = 30000;
export const SALARY_DRIVER = 10000;
export const SALARY_HELPER = 7000;
export const TOTAL_SALARIES = SALARY_DRIVER + SALARY_HELPER;
